server {
    listen 50990;
    server_name _;

    # Чтобы url_for НЕ генерировал localhost
    proxy_set_header Host $host:$server_port;
    
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    #include /etc/nginx/mime.types;

    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_buffers 16 8k;
    gzip_comp_level 6;
    gzip_http_version 1.1;
    gzip_min_length 512;
    gzip_types text/plain text/xml text/javascript text/css font/ttf 
               application/xml application/json application/manifest+json application/javascript
               application/rdf+xml application/rss+xml;
    
    access_log /var/log/nginx/nginx-irr-access.log;
    error_log /var/log/nginx/nginx-irr-error.log;
    
    client_max_body_size 10M;
    charset utf-8;

    
    # === ПРОКСИ НА FASTAPI ===
    location / {
        proxy_pass http://127.0.0.1:50991;
        # Чтобы не было проблем с длинными ответами
        proxy_buffering off;
    }
}